// ============================================================================
//  topology_test.cpp
//  Phase 3 test: instantiate the buck topology TEMPLATE into an unbound
//  ir::Design and prove it is electrically equivalent to the hand-built
//  fixture from Phases 1-2 (same nets, same role/pin wiring), differing only
//  in auto-generated reference designators.
//
//  Build:
//    g++ -std=c++17 -I synth synth/tests/topology_test.cpp -o build/topology_test
//  Run:
//    ./build/topology_test
// ============================================================================

#include "electrical_ir.h"
#include "ir_validate.h"
#include "ir_dump.h"
#include "topology_library.h"
#include "topology_instantiate.h"
#include "tests/buck_fixture.h"

#include <cassert>
#include <iostream>
#include <map>
#include <set>
#include <string>

using namespace ir;

// A designator-independent electrical signature:
//   node name -> set of "ROLE.pin" terminals attached to it.
// Two designs with the same signature are electrically the same circuit
// regardless of how their reference designators (Q1 vs Cin) were named.
static std::map<std::string, std::set<std::string>> NetSignature(const Design& d) {
    std::map<std::string, std::set<std::string>> sig;
    for (const auto& c : d.components) {
        for (const auto& p : c.pins) {
            if (p.node == INVALID_NODE) continue;
            sig[d.nodes[p.node].name].insert(c.role + "." + p.name);
        }
    }
    return sig;
}

static int CountByPrefix(const Design& d, char prefix) {
    int n = 0;
    for (const auto& c : d.components) {
        if (!c.ref.empty() && c.ref[0] == prefix) ++n;
    }
    return n;
}

int main() {
    // Instantiate from the stored topology template.
    topo::Topology t = topo::BuildBuckTopology();
    Design inst = topo::Instantiate(t);

    Dump(inst);
    ValidationReport report = Validate(inst);
    DumpReport(report);

    // ---- Structural validity (unbound warnings expected) ---------------
    assert(report.ok() && "Instantiated topology must be structurally valid");

    // ---- Same nodes and component count as the fixture -----------------
    Design fixture = BuildBuckPowerStage();
    assert(inst.nodes.size() == fixture.nodes.size() && "node count mismatch");
    assert(inst.components.size() == fixture.components.size() && "component count mismatch");

    // ---- Reference designators auto-generated by type ------------------
    assert(CountByPrefix(inst, 'Q') == 1 && "expected 1 MOSFET (Q1)");
    assert(CountByPrefix(inst, 'D') == 1 && "expected 1 diode (D1)");
    assert(CountByPrefix(inst, 'L') == 1 && "expected 1 inductor (L1)");
    assert(CountByPrefix(inst, 'C') == 2 && "expected 2 caps (C1, C2)");
    assert(CountByPrefix(inst, 'R') == 1 && "expected 1 resistor (R1)");
    assert(inst.FindComponent("Q1") && inst.FindComponent("C1") &&
           inst.FindComponent("C2") && "expected canonical designators");

    // ---- Electrical equivalence to the hand-built fixture --------------
    // (Same wiring by role+pin, independent of designator naming.)
    auto sig_inst    = NetSignature(inst);
    auto sig_fixture = NetSignature(fixture);
    assert(sig_inst == sig_fixture &&
           "Instantiated topology is not electrically equivalent to the fixture");

    // ---- Everything still unbound (no MPNs yet) ------------------------
    for (const auto& c : inst.components) assert(!c.IsBound());

    std::cout << "\n[PASS] Phase 3: topology instantiation test passed.\n";
    return 0;
}
